import { Genkit } from 'genkit';
import { modelRef, GenerationCommonConfigSchema } from 'genkit/model';
import { z } from 'genkit';
import fs from 'fs';

const DEFAULT_HF_INFERENCE_ENDPOINT = 'https://router.huggingface.co/hf-inference/models/';

export const HuggingFaceConfigSchema = GenerationCommonConfigSchema.extend({
    model: z.string().optional(),
    hfInferenceEndpoint: z.string().optional(),
});

export const huggingFaceModel = (modelName: string) =>
    modelRef({
        name: `huggingface/${modelName}`,
        info: {
            label: `Hugging Face: ${modelName}`,
            supports: {
                multiturn: true,
                systemRole: true,
                output: ['text'],
            },
        },
        configSchema: HuggingFaceConfigSchema,
    });

export function huggingfaceProvider(options: { apiKey: string }) {
    return (ai: Genkit) => ({
        name: 'huggingfaceProvider',
        initializer: async () => {
            ai.defineModel(
                {
                    name: 'huggingface-gateway',
                    label: 'Hugging Face API Gateway',
                    supports: {
                        multiturn: true,
                        systemRole: true,
                        output: ['text'],
                    },
                    configSchema: HuggingFaceConfigSchema,
                },
                async (request) => {
                    const modelName = request.config?.model || 'google/medgemma-1.5-4b-it';
                    const endpoint = `${DEFAULT_HF_INFERENCE_ENDPOINT}${modelName}`;

                    const debugLog = (msg: string) => {
                        console.log(msg);
                        fs.appendFileSync('adapter_debug.log', msg + '\n');
                    };

                    debugLog(`[HF Adapter] Request Started: ${new Date().toISOString()}`);
                    debugLog(`[HF Adapter] Endpoint: ${endpoint}`);
                    debugLog(`[HF Adapter] Using model: ${modelName}`);
                    debugLog(`[HF Adapter] API Key loaded? ${!!options.apiKey}`);
                    if (options.apiKey) {
                        debugLog(`[HF Adapter] API Key length: ${options.apiKey.length}`);
                        debugLog(`[HF Adapter] API Key prefix: ${options.apiKey.substring(0, 5)}`);
                    }

                    const messages = request.messages
                        .map((m) => `${m.role}: ${m.content[0].text}`)
                        .join('\n');

                    const hfRequest = {
                        inputs: messages,
                        parameters: {
                            max_new_tokens: request.config?.maxOutputTokens || 1024,
                            temperature: request.config?.temperature || 0.7,
                            top_p: request.config?.topP || 0.9,
                            return_full_text: false,
                        },
                    };

                    debugLog(`[HF Adapter] Request Body: ${JSON.stringify(hfRequest)}`);

                    const response = await fetch(endpoint, {
                        method: 'POST',
                        headers: {
                            Authorization: `Bearer ${options.apiKey}`,
                            'Content-Type': 'application/json',
                        },
                        body: JSON.stringify(hfRequest),
                    });

                    if (!response.ok) {
                        const error = await response.text();
                        throw new Error(`Hugging Face API error (${response.status}): ${error}`);
                    }

                    const result = await response.json();

                    const generatedText = Array.isArray(result)
                        ? result[0]?.generated_text
                        : result.generated_text;

                    if (!generatedText) {
                        throw new Error('No text generated by Hugging Face');
                    }

                    return {
                        candidates: [
                            {
                                index: 0,
                                finishReason: 'stop',
                                message: {
                                    role: 'model',
                                    content: [{ text: generatedText }],
                                },
                            },
                        ],
                    };
                }
            );
        }
    });
}
